# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: amandat.art
email: amanda@thomason.email
description: Work in progress
baseurl: ""
url: "https://amandat-art.github.io" # temporary url

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username:
twitter_username:
facebook_URL:
instagram_username: amandat.art
dribbble_username:
500px_username:
phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
