---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Main
- type: document
  path: src/content/index.html
  label: Home
- type: document
  path: src/data/site.json
  label: Configuration
  match: "**/*"
- type: heading
  label: Portfolio
- type: directory
  path: src/content/portfolio
  label: Featured images
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - featured-image
- type: document
  path: src/content/portfolio/portfolio.11tydata.json
  label: Configuration
- type: heading
  label: code
- type: directory
  path: src/includes
  label: Includes
  create: all
  match: "**/*"
  new_doc_ext: html
upload_dir: src/images
public_path: "/portfolio/assets/images"
front_matter_path: "/assets/images"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx @11ty/eleventy --serve
